services:
  phpfpm:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    container_name: magento-phpfpm-1
    volumes:
      - ./magento:/var/www/html
    networks:
      - webnet

  nginx:
    image: nginx:stable
    container_name: magento-nginx-1
    ports:
      - "8080:80"
    volumes:
      - ./magento:/var/www/html
      - ./nginx-app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
