nginx:
  image: nginx:stable
  container_name: magento-nginx-1
  ports:
    - "8080:80"  # Map host port 8080 to container port 80
  volumes:
    - ./magento:/var/www/html          # Magento source code
    - ./nginx-app/nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
  depends_on:
    - phpfpm
  networks:
    - webnet
