name: Magento 2 CI/CD

on:
  push:
    branches: [ main ]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    name: Magento 2 build & tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Magento build (NO install, NO DB)
        uses: MAD-I-T/magento-actions@v3.29
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        with:
          process: build
          magento_only: 1
          no_push: 1
