name: Magento 2 CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    name: "Magento 2 build & tests"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Magento CI build (existing project)
        uses: MAD-I-T/magento-actions@v3.29
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        with:
          process: build
          magento_only: true
          php: "8.2"
          no_push: true
