name: Magento 2 CI/CD Docker

on:
  push:
    branches:
      - main

jobs:
  build_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build Magento Docker image
      - name: Build Magento Docker image
        run: docker build -t magento:latest ./dockerfiles

      # 3. Login to AWS ECR
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
          region: us-east-1

      # 4. Tag & push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker tag magento:latest ${{ secrets.ECR_REGISTRY }}/magento:latest
          docker push ${{ secrets.ECR_REGISTRY }}/magento:latest

  deploy:
    name: Deploy to Kubernetes (EKS)
    needs: build_push
    runs-on: ubuntu-latest

    steps:
      # 1. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 2. Update EKS kubeconfig
      - name: Update Kubernetes config
        run: |
          aws eks update-kubeconfig --name prod-eks-cluster --region us-east-1

      # 3. Set Magento deployment image to the new ECR image
      - name: Deploy Magento container
        run: |
          kubectl set image deployment/magento magento=${{ secrets.ECR_REGISTRY }}/magento:latest
          kubectl rollout status deployment/magento
