name: Magento 2 CI/CD

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Magento 2 Build & Test

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Magento CI Build
        uses: MAD-I-T/magento-actions@v3.29
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        with:
          process: build
          magento_only: 1
          no_push: 1

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/magento2
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php bin/magento setup:upgrade
            php bin/magento setup:di:compile
            php bin/magento cache:flush
